---
- hosts: all
  tasks:
    - name: Insert /etc/hosts
      blockinfile:
        path: /etc/hosts
        block: |
          192.168.0.20 node-1.devops.com node-1
          192.168.0.21 node-2.devops.com node-2
         
    - name: Disable SELinux
      selinux:
        state: disabled
    - name: Install the wget
      yum: name=wget state=latest
    - name: Stop and disable firewalld.
      service: name=firewalld state=stopped enabled=False
    - name: stop neywork-manager and disable
      service: name=NetworkManager state=stopped enabled=no
    - name: Remove swapfile from /etc/fstab
      mount:
        name: swap
        fstype: swap
        state: absent
    - name: Disable swap
      command: swapoff -a
    - name: Install NTP
      yum: name=ntp,ntpdate state=present update_cache=yes
    - name: Make sure NTP is started up
      service: name=ntpd state=started enabled=yes
    - name: restart ntp
      service: name=ntpd state=restarted

    - name: install some components
      command: yum install device-mapper-persistent-data lvm2 wget telnet net-tools yum-utils  yum-plugin-ovl -y
    - name: adding repo
      command: sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    - name: install docker
      command: sudo yum install docker-ce docker-ce-cli containerd.io
    - name: start the serivce
      systemd: name=docker state=started
    - name: Enable docker
      systemd: name=docker enabled=yes

   


